services:
  - type: web
    name: laravel-portfolio
    env: docker
    region: singapore
    plan: free
    envVars:
      - key: APP_NAME
        value: Portfolio
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:bRkZDG6VkdgkuzLA5kSjtd+Vv4SA8clA73TlH5w9moM=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: portfolio-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portfolio-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: portfolio-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: portfolio-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: free
    region: singapore
